### ISSUE TITLE
Javaslatok/értékelés

### ISSUE THREAD

**Issue by LoremIPsummer** [Uni-Sopron/termelesiranyitas-o22-timetable-ga#1]

**Comment by oliverosz** [comment]
@LoremIPsummer A `config.ini`-ben csak a solver beállításainak lenne a helye. A bemeneti adatokat jobb lenne cmdline argként megadott fájlból beolvasni.

A kódhoz írtam még néhány megjegyzést a commitnál, de egyébként nagyon szép munka! @hegyhati szerintem mehet neki az 5-ös.

**Comment by hegyhati** [comment]
Neptunba bevesve.
